apiVersion: v1
kind: pod
metadata:
  name: hello-pod
spec:
#list of containers
  containers:
  - name: hello
    image: nginx
    ports: #this line will not open any ports, only for information(generatlly nginx will open 80)
    - containerPort: 80