apiVersion: v1
kind: pod
metadata:
  name: multi
spec:
  containers:
  - name: nginx container
    image: nginx
    ports:
    - containerPort: 80
  - name: alma
    image: almalinux:8
    command: ["sleep", "300"] #it is os, will exit immediately without sleep command
    