apiVersion: v1
kind: pod
metadata:
  name: environment
  labels:
    bsk: "label1"
spec:
  containers:
  - name: demo
    image: nginx:8
    env:
    - name: greeting
      value: "hello from pod"
    - name: wish
      value: "good morning"
